map_memory_node:
  ros__parameters:
    resolution: 0.3
    width: 200
    height: 200
    frame_id: "sim_world"
    update_distance: 1.5
    publish_period_ms: 1000
    costmap_topic: "/costmap"
    odom_topic: "/odom/filtered"
    map_topic: "/map"
